DROP INDEX IF EXISTS `areas_to_generate_min_x_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `areas_to_generate_min_y_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `areas_to_generate_max_x_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `areas_to_generate_max_y_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `lidar_step_jobs_index_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `map_rendering_step_jobs_index_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `pyramid_rendering_step_jobs_index_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `pyramid_rendering_step_jobs_x_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `pyramid_rendering_step_jobs_y_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `pyramid_rendering_step_jobs_zoom_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `pyramid_rendering_step_jobs_status_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `pyramid_rendering_step_jobs_start_time_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_min_x_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_min_y_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_max_x_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_max_y_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_lidar_step_status_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_lidar_step_start_time_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_map_rendering_step_status_index`;--> statement-breakpoint
DROP INDEX IF EXISTS `tiles_map_rendering_step_start_time_index`;